[package]
name = "sui-zklogin-ffi"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
bcs = "0.1.6"
base64ct = "1.8.3"
sha2 = "0.10.9"
serde_json = "1.0.145"
sui-crypto = { path = "../sui-crypto", features = ["zklogin", "bls12381", "ed25519", "secp256r1", "secp256k1"] }
sui-sdk-types = { path = "../sui-sdk-types", features = ["serde"] }
